package com.devenlucaz.doscom.character

enum class PropType {
    NONE, PARTY_HAT, SUNGLASSES, PILOT_HAT,
    DETECTIVE_HAT, PIRATE_HAT, OVERSIZED_GLASSES,
    BOOK, FISHING_ROD, TREASURE_MAP, MAGNIFYING_GLASS,
    BOOMBOX, TINY_PHONE, TINY_CAKE, PARTY_HORN,
    CARDBOARD_SWORD, BINOCULARS, UMBRELLA,
    FLASHLIGHT, ABACUS, GIFT_BOX
}
